insert into books (isbn, title, author, cover, URL) values ('22-208-6130', 'Fortress', 'Rubin Mosey', 'http://dummyimage.com/194x200.bmp/5fa2dd/ffffff', 'https://artisteer.com');
insert into books (isbn, title, author, cover, URL) values ('78-928-5988', 'All About Eve', 'Ced Yard', 'http://dummyimage.com/249x211.jpg/dddddd/000000', 'http://irs.gov');
insert into books (isbn, title, author, cover, URL) values ('11-665-6893', 'Pianomania', 'Riva Peplay', 'http://dummyimage.com/102x191.jpg/5fa2dd/ffffff', 'http://shinystat.com');
insert into books (isbn, title, author, cover, URL) values ('81-762-6832', 'Stanley & Iris', 'Augustine Siemandl', 'http://dummyimage.com/209x176.bmp/cc0000/ffffff', 'http://slate.com');
insert into books (isbn, title, author, cover, URL) values ('32-784-6217', 'Step Into Liquid', 'Megen Jaze', 'http://dummyimage.com/149x186.jpg/ff4444/ffffff', 'https://businesswire.com');
insert into books (isbn, title, author, cover, URL) values ('90-816-1771', 'Rare Birds', 'Pembroke McKibben', 'http://dummyimage.com/119x174.jpg/cc0000/ffffff', 'https://shop-pro.jp');
insert into books (isbn, title, author, cover, URL) values ('33-085-3406', 'Van, The', 'Giselbert Arthur', 'http://dummyimage.com/153x227.bmp/ff4444/ffffff', 'http://etsy.com');
insert into books (isbn, title, author, cover, URL) values ('74-304-7626', 'Curiosity of Chance, The', 'Saundra Trawin', 'http://dummyimage.com/162x169.bmp/ff4444/ffffff', 'https://omniture.com');
insert into books (isbn, title, author, cover, URL) values ('45-907-8120', 'R.S.V.P. ', 'Kirk Barras', 'http://dummyimage.com/247x145.jpg/cc0000/ffffff', 'http://naver.com');
insert into books (isbn, title, author, cover, URL) values ('41-875-0688', 'Maidens in Uniform (Mädchen in Uniform)', 'Eberto O'' Cloney', 'http://dummyimage.com/186x123.png/dddddd/000000', 'http://cyberchimps.com');
insert into books (isbn, title, author, cover, URL) values ('66-370-4951', 'Death Becomes Her', 'Godwin Stanfield', 'http://dummyimage.com/114x235.jpg/cc0000/ffffff', 'http://constantcontact.com');
insert into books (isbn, title, author, cover, URL) values ('69-532-9161', 'Wings (Krylya)', 'Tomkin Meadley', 'http://dummyimage.com/116x210.bmp/ff4444/ffffff', 'https://naver.com');
insert into books (isbn, title, author, cover, URL) values ('17-964-2417', 'Back Stage', 'Matt Canfer', 'http://dummyimage.com/148x146.bmp/ff4444/ffffff', 'http://slideshare.net');
insert into books (isbn, title, author, cover, URL) values ('84-390-8096', 'Match Factory Girl, The (Tulitikkutehtaan tyttö)', 'Parrnell Fetherston', 'http://dummyimage.com/180x178.jpg/cc0000/ffffff', 'http://who.int');
insert into books (isbn, title, author, cover, URL) values ('14-263-2447', 'Barton Fink', 'Kerrin Oleksinski', 'http://dummyimage.com/244x242.jpg/5fa2dd/ffffff', 'https://ask.com');
insert into books (isbn, title, author, cover, URL) values ('74-558-4868', 'Likeable Mister R, The (Simpaticul domn R)', 'Selena Kynge', 'http://dummyimage.com/102x233.bmp/5fa2dd/ffffff', 'http://nbcnews.com');
insert into books (isbn, title, author, cover, URL) values ('79-017-7087', 'The Returned', 'Sigismund Ferrand', 'http://dummyimage.com/153x194.jpg/dddddd/000000', 'http://stanford.edu');
insert into books (isbn, title, author, cover, URL) values ('09-420-8087', 'Assassin(s)', 'Cristina Braune', 'http://dummyimage.com/219x216.jpg/cc0000/ffffff', 'https://ft.com');
insert into books (isbn, title, author, cover, URL) values ('63-244-8037', 'Fast Food', 'Nanni Roelofs', 'http://dummyimage.com/132x141.bmp/5fa2dd/ffffff', 'https://gizmodo.com');
insert into books (isbn, title, author, cover, URL) values ('75-968-7175', 'Children of the Night', 'Shawn Volcker', 'http://dummyimage.com/155x176.jpg/5fa2dd/ffffff', 'https://eepurl.com');
insert into books (isbn, title, author, cover, URL) values ('81-176-0483', 'Take Out', 'Emmye Godfroy', 'http://dummyimage.com/249x138.jpg/ff4444/ffffff', 'http://1688.com');
insert into books (isbn, title, author, cover, URL) values ('99-227-3790', 'Four Days of Naples, The (Le quattro giornate di Napoli)', 'Delila Turmell', 'http://dummyimage.com/145x166.jpg/dddddd/000000', 'http://digg.com');
insert into books (isbn, title, author, cover, URL) values ('59-175-9152', 'At Sea', 'Shelbi Rabb', 'http://dummyimage.com/160x225.bmp/dddddd/000000', 'http://cnn.com');
insert into books (isbn, title, author, cover, URL) values ('83-462-8637', 'Me Myself I', 'Michael O Mullen', 'http://dummyimage.com/250x107.jpg/dddddd/000000', 'http://tumblr.com');
insert into books (isbn, title, author, cover, URL) values ('39-396-1920', 'Kolberg', 'Derek Hubery', 'http://dummyimage.com/128x120.jpg/cc0000/ffffff', 'https://github.io');
insert into books (isbn, title, author, cover, URL) values ('99-871-8702', 'Battle of Russia, The (Why We Fight, 5)', 'Konstance Clarkin', 'http://dummyimage.com/150x245.jpg/cc0000/ffffff', 'http://themeforest.net');
insert into books (isbn, title, author, cover, URL) values ('32-974-3171', 'Seven Year Itch, The', 'Gusti Blaszkiewicz', 'http://dummyimage.com/137x111.png/cc0000/ffffff', 'https://so-net.ne.jp');
insert into books (isbn, title, author, cover, URL) values ('37-445-9787', 'Town Without Pity', 'Nerti Isgate', 'http://dummyimage.com/215x143.jpg/dddddd/000000', 'https://cbc.ca');
insert into books (isbn, title, author, cover, URL) values ('83-498-2296', 'At First Sight', 'Domenico Joerning', 'http://dummyimage.com/105x148.bmp/ff4444/ffffff', 'https://ibm.com');
insert into books (isbn, title, author, cover, URL) values ('79-809-4399', 'Male Domination', 'Harper Patillo', 'http://dummyimage.com/208x208.jpg/cc0000/ffffff', 'https://miitbeian.gov.cn');
insert into books (isbn, title, author, cover, URL) values ('57-052-5884', 'Road, The', 'Josephine Marklew', 'http://dummyimage.com/108x110.bmp/dddddd/000000', 'https://mapquest.com');
insert into books (isbn, title, author, cover, URL) values ('58-693-7997', 'You Again', 'Blondie Crighton', 'http://dummyimage.com/242x169.png/5fa2dd/ffffff', 'http://economist.com');
insert into books (isbn, title, author, cover, URL) values ('75-425-4572', 'Patsy, The', 'Clemmy Silvester', 'http://dummyimage.com/247x219.png/cc0000/ffffff', 'https://trellian.com');
insert into books (isbn, title, author, cover, URL) values ('62-773-7610', 'Night on Earth', 'Robbie Meddemmen', 'http://dummyimage.com/168x205.jpg/ff4444/ffffff', 'https://nymag.com');
insert into books (isbn, title, author, cover, URL) values ('56-174-5187', 'Scanners II: The New Order', 'Waylan Tackley', 'http://dummyimage.com/239x171.png/cc0000/ffffff', 'http://ebay.com');
insert into books (isbn, title, author, cover, URL) values ('93-828-5359', 'Stepmom', 'Jordanna Francillo', 'http://dummyimage.com/209x126.png/dddddd/000000', 'http://jimdo.com');
insert into books (isbn, title, author, cover, URL) values ('12-260-2604', 'Decoys 2: Alien Seduction ', 'Vaughan Caplis', 'http://dummyimage.com/191x249.bmp/ff4444/ffffff', 'http://pagesperso-orange.fr');
insert into books (isbn, title, author, cover, URL) values ('26-674-9243', 'Restraint', 'Barty Hanssmann', 'http://dummyimage.com/163x216.jpg/ff4444/ffffff', 'https://newsvine.com');
insert into books (isbn, title, author, cover, URL) values ('57-961-1289', 'Hungry for Change', 'Nannie Dockwray', 'http://dummyimage.com/212x146.png/cc0000/ffffff', 'https://weather.com');
insert into books (isbn, title, author, cover, URL) values ('60-037-2836', 'Batman: Assault on Arkham', 'Nowell Quince', 'http://dummyimage.com/246x130.jpg/cc0000/ffffff', 'https://cisco.com');
insert into books (isbn, title, author, cover, URL) values ('61-494-3000', 'Deceived', 'Andi Dron', 'http://dummyimage.com/243x183.bmp/ff4444/ffffff', 'https://kickstarter.com');
insert into books (isbn, title, author, cover, URL) values ('09-722-1846', 'Blume in Love', 'Morly De Beneditti', 'http://dummyimage.com/141x188.jpg/dddddd/000000', 'https://google.ca');
insert into books (isbn, title, author, cover, URL) values ('60-123-0437', 'Why Not Me? (Pourquoi pas moi ?)', 'Enos Biggin', 'http://dummyimage.com/242x171.bmp/cc0000/ffffff', 'http://time.com');
insert into books (isbn, title, author, cover, URL) values ('34-681-2354', 'Don 2', 'Andreana Gealy', 'http://dummyimage.com/243x185.png/5fa2dd/ffffff', 'http://cbc.ca');
insert into books (isbn, title, author, cover, URL) values ('80-461-3528', 'Aerial, The (La antena)', 'Johnath Martensen', 'http://dummyimage.com/220x215.png/5fa2dd/ffffff', 'https://ameblo.jp');
insert into books (isbn, title, author, cover, URL) values ('05-942-6823', 'Magic Camp', 'Fields Skitch', 'http://dummyimage.com/133x118.jpg/cc0000/ffffff', 'http://dmoz.org');
insert into books (isbn, title, author, cover, URL) values ('93-427-0800', 'Adventures of Tintin, The', 'Parry Fairfoull', 'http://dummyimage.com/231x133.jpg/5fa2dd/ffffff', 'https://imgur.com');
insert into books (isbn, title, author, cover, URL) values ('17-305-6569', 'Stargate', 'Emiline Gundry', 'http://dummyimage.com/211x229.png/ff4444/ffffff', 'http://hhs.gov');
insert into books (isbn, title, author, cover, URL) values ('11-339-5275', 'Black Scorpion, The', 'Teresina Latty', 'http://dummyimage.com/221x242.jpg/5fa2dd/ffffff', 'http://google.com.hk');
insert into books (isbn, title, author, cover, URL) values ('68-497-4458', 'Vinyl', 'Stesha Bonar', 'http://dummyimage.com/163x213.bmp/cc0000/ffffff', 'https://studiopress.com');
insert into books (isbn, title, author, cover, URL) values ('49-307-0416', 'Beau Brummel', 'Giustina Tacey', 'http://dummyimage.com/230x162.bmp/dddddd/000000', 'http://stanford.edu');
insert into books (isbn, title, author, cover, URL) values ('01-213-5169', 'Detention', 'Pandora Botcherby', 'http://dummyimage.com/140x204.png/ff4444/ffffff', 'https://time.com');
insert into books (isbn, title, author, cover, URL) values ('50-010-5365', 'Katze im Sack', 'Caty Hanstock', 'http://dummyimage.com/154x172.png/cc0000/ffffff', 'https://meetup.com');
insert into books (isbn, title, author, cover, URL) values ('32-844-6929', 'Addams Family Reunion', 'Anjanette Standingford', 'http://dummyimage.com/243x155.bmp/5fa2dd/ffffff', 'https://seattletimes.com');
insert into books (isbn, title, author, cover, URL) values ('21-363-5867', '12 Angry Men', 'Sharona Dutch', 'http://dummyimage.com/234x163.bmp/cc0000/ffffff', 'http://nhs.uk');
insert into books (isbn, title, author, cover, URL) values ('07-349-0676', 'Calamari Union', 'Melodee Balsellie', 'http://dummyimage.com/210x119.bmp/dddddd/000000', 'https://earthlink.net');
insert into books (isbn, title, author, cover, URL) values ('70-102-3885', 'Winter Soldier', 'Jere Gerrans', 'http://dummyimage.com/121x219.jpg/5fa2dd/ffffff', 'https://jimdo.com');
insert into books (isbn, title, author, cover, URL) values ('04-098-7858', 'India (Indien)', 'Ellary Thorold', 'http://dummyimage.com/113x194.jpg/cc0000/ffffff', 'http://jigsy.com');
insert into books (isbn, title, author, cover, URL) values ('66-744-5118', 'I Saw the Devil (Akmareul boatda)', 'Templeton Ivashinnikov', 'http://dummyimage.com/155x245.bmp/5fa2dd/ffffff', 'https://tamu.edu');
insert into books (isbn, title, author, cover, URL) values ('13-844-3112', 'Culture High, The', 'Krystyna Merwede', 'http://dummyimage.com/105x224.bmp/5fa2dd/ffffff', 'https://cnet.com');
insert into books (isbn, title, author, cover, URL) values ('59-851-1769', 'Fallen', 'Elmer Bridgwater', 'http://dummyimage.com/144x230.bmp/dddddd/000000', 'https://wp.com');
insert into books (isbn, title, author, cover, URL) values ('23-454-8282', 'Love at Large', 'Etheline Winkless', 'http://dummyimage.com/130x116.bmp/cc0000/ffffff', 'https://twitter.com');
insert into books (isbn, title, author, cover, URL) values ('56-331-4722', 'Amen', 'Nancy Hellwig', 'http://dummyimage.com/217x129.jpg/dddddd/000000', 'https://oakley.com');
insert into books (isbn, title, author, cover, URL) values ('34-880-1603', 'Psychomania (Death Wheelers, The)', 'Editha Baldoni', 'http://dummyimage.com/249x174.jpg/cc0000/ffffff', 'http://howstuffworks.com');
insert into books (isbn, title, author, cover, URL) values ('04-181-9353', 'Virtuality', 'Cristie Jenckes', 'http://dummyimage.com/195x112.bmp/5fa2dd/ffffff', 'https://unc.edu');
insert into books (isbn, title, author, cover, URL) values ('86-842-9074', 'Eloise at Christmastime', 'Brock Adlington', 'http://dummyimage.com/101x125.png/dddddd/000000', 'https://com.com');
insert into books (isbn, title, author, cover, URL) values ('37-495-1812', 'Ghostmaker, The (Box of Shadows)', 'Scarlett Souster', 'http://dummyimage.com/152x145.png/cc0000/ffffff', 'https://psu.edu');
insert into books (isbn, title, author, cover, URL) values ('34-296-5254', 'One Good Cop', 'Hewitt Foston', 'http://dummyimage.com/116x154.bmp/5fa2dd/ffffff', 'https://who.int');
insert into books (isbn, title, author, cover, URL) values ('06-083-4703', 'Come Sweet Death (Komm, süsser Tod)', 'Margaret Rossborough', 'http://dummyimage.com/185x199.png/5fa2dd/ffffff', 'http://cafepress.com');
insert into books (isbn, title, author, cover, URL) values ('13-232-0404', 'In Therapy (Divã)', 'Angelico Klimowicz', 'http://dummyimage.com/225x117.png/cc0000/ffffff', 'http://yellowbook.com');
insert into books (isbn, title, author, cover, URL) values ('49-097-0023', 'Stone Angel, The', 'Blancha Antoniewicz', 'http://dummyimage.com/101x117.bmp/dddddd/000000', 'http://reuters.com');
insert into books (isbn, title, author, cover, URL) values ('31-154-3943', 'Bride of Re-Animator', 'Madelon Santi', 'http://dummyimage.com/218x179.bmp/ff4444/ffffff', 'https://shop-pro.jp');
insert into books (isbn, title, author, cover, URL) values ('92-791-5539', 'Newsfront', 'Jennifer Dilley', 'http://dummyimage.com/214x136.jpg/5fa2dd/ffffff', 'http://ted.com');
insert into books (isbn, title, author, cover, URL) values ('83-554-7526', 'Wild Oranges', 'Matthiew Pruvost', 'http://dummyimage.com/161x236.png/5fa2dd/ffffff', 'http://spotify.com');
insert into books (isbn, title, author, cover, URL) values ('31-726-3465', 'Hava Nagila: The Movie', 'Kirk Mollene', 'http://dummyimage.com/228x132.png/5fa2dd/ffffff', 'http://mashable.com');
insert into books (isbn, title, author, cover, URL) values ('84-891-8947', 'Stella Does Tricks', 'Bev Crufts', 'http://dummyimage.com/224x123.bmp/dddddd/000000', 'http://dyndns.org');
insert into books (isbn, title, author, cover, URL) values ('75-192-6237', 'Willow Creek', 'Odette Conville', 'http://dummyimage.com/227x249.bmp/dddddd/000000', 'http://unesco.org');
insert into books (isbn, title, author, cover, URL) values ('91-917-7909', 'Hobbit: The Desolation of Smaug, The', 'Ryan Beardon', 'http://dummyimage.com/183x202.png/5fa2dd/ffffff', 'https://chicagotribune.com');
insert into books (isbn, title, author, cover, URL) values ('14-440-3395', 'Bolero', 'Bendite Hedgeman', 'http://dummyimage.com/239x100.jpg/cc0000/ffffff', 'http://globo.com');
insert into books (isbn, title, author, cover, URL) values ('69-111-0030', 'Police Story 2 (Ging chaat goo si juk jaap)', 'Evangelin Maundrell', 'http://dummyimage.com/195x117.bmp/dddddd/000000', 'https://taobao.com');
insert into books (isbn, title, author, cover, URL) values ('63-872-5485', 'So Young (Zhi wo men zhong jiang shi qu de qing chun)', 'Cecilla Rougier', 'http://dummyimage.com/187x214.jpg/dddddd/000000', 'https://omniture.com');
insert into books (isbn, title, author, cover, URL) values ('63-075-6407', 'Touch of Class, A', 'Willa Berthe', 'http://dummyimage.com/211x106.png/ff4444/ffffff', 'https://imageshack.us');
insert into books (isbn, title, author, cover, URL) values ('99-652-2372', 'Alive and Ticking (Ein Tick anders)', 'Brigit Shapiro', 'http://dummyimage.com/137x198.png/5fa2dd/ffffff', 'http://dailymotion.com');
insert into books (isbn, title, author, cover, URL) values ('81-221-2366', 'Housebound', 'Alfons Ortes', 'http://dummyimage.com/157x206.bmp/dddddd/000000', 'http://blog.com');
insert into books (isbn, title, author, cover, URL) values ('82-218-3944', 'Branded', 'Rebecca Ygo', 'http://dummyimage.com/162x231.png/dddddd/000000', 'https://addtoany.com');
insert into books (isbn, title, author, cover, URL) values ('71-550-3374', 'Welcome to Sarajevo', 'Tandie Gerbi', 'http://dummyimage.com/125x142.png/ff4444/ffffff', 'https://list-manage.com');
insert into books (isbn, title, author, cover, URL) values ('58-889-4744', 'My Mother''s Courage (Mutters Courage)', 'Maribeth Allchorne', 'http://dummyimage.com/112x137.png/5fa2dd/ffffff', 'http://addthis.com');
insert into books (isbn, title, author, cover, URL) values ('34-939-1251', 'Hey Ram', 'Dore Bennis', 'http://dummyimage.com/212x222.jpg/5fa2dd/ffffff', 'http://weather.com');
insert into books (isbn, title, author, cover, URL) values ('47-075-7043', 'Tightrope', 'Lynette Sisland', 'http://dummyimage.com/209x115.jpg/5fa2dd/ffffff', 'https://bloglovin.com');
insert into books (isbn, title, author, cover, URL) values ('71-130-7796', 'Seventh Heaven (Septième ciel, Le)', 'Maxwell Pfaffel', 'http://dummyimage.com/199x137.jpg/5fa2dd/ffffff', 'https://jugem.jp');
insert into books (isbn, title, author, cover, URL) values ('86-416-6752', 'For Heaven''s Sake', 'Merline O''Lunney', 'http://dummyimage.com/195x248.png/cc0000/ffffff', 'https://dell.com');
insert into books (isbn, title, author, cover, URL) values ('81-142-4649', 'Mr Reliable', 'Rafferty Gammet', 'http://dummyimage.com/189x209.bmp/cc0000/ffffff', 'http://squidoo.com');
insert into books (isbn, title, author, cover, URL) values ('85-918-8051', 'Oklahoma Crude', 'Martguerita Mcimmie', 'http://dummyimage.com/155x119.jpg/5fa2dd/ffffff', 'https://npr.org');
insert into books (isbn, title, author, cover, URL) values ('28-576-7458', 'Saint John of Las Vegas', 'Germaine Balston', 'http://dummyimage.com/221x210.bmp/5fa2dd/ffffff', 'https://scientificamerican.com');
insert into books (isbn, title, author, cover, URL) values ('34-605-8062', 'Kvarteret Skatan reser till Laholm', 'Griff Pinkstone', 'http://dummyimage.com/218x134.bmp/5fa2dd/ffffff', 'http://arstechnica.com');
insert into books (isbn, title, author, cover, URL) values ('65-835-1099', 'Brick Mansions', 'Andras Oxtiby', 'http://dummyimage.com/189x113.png/ff4444/ffffff', 'http://aboutads.info');
insert into books (isbn, title, author, cover, URL) values ('37-002-0420', 'Daisies (Sedmikrasky)', 'Jonathon Scarsbrick', 'http://dummyimage.com/178x102.bmp/dddddd/000000', 'https://booking.com');
insert into books (isbn, title, author, cover, URL) values ('50-264-8496', 'Memories of Murder (Salinui chueok)', 'Reba Sweeting', 'http://dummyimage.com/223x127.bmp/cc0000/ffffff', 'http://google.ca');
insert into books (isbn, title, author, cover, URL) values ('05-145-9085', 'Songs From the Second Floor (Sånger från andra våningen)', 'Mahmud Olliar', 'http://dummyimage.com/210x219.bmp/cc0000/ffffff', 'https://nationalgeographic.com');
insert into books (isbn, title, author, cover, URL) values ('36-280-0953', 'Signos del zodiaco, Los', 'Matti Smithies', 'http://dummyimage.com/142x209.jpg/dddddd/000000', 'http://wikispaces.com');
insert into books (isbn, title, author, cover, URL) values ('48-050-5229', 'Ploy', 'Byrann Livingstone', 'http://dummyimage.com/238x189.png/ff4444/ffffff', 'https://eventbrite.com');
insert into books (isbn, title, author, cover, URL) values ('83-519-3186', 'Garage Sale Mystery', 'Taylor Gerardin', 'http://dummyimage.com/199x145.jpg/cc0000/ffffff', 'https://shutterfly.com');
insert into books (isbn, title, author, cover, URL) values ('52-343-8251', 'Camp de Thiaroye', 'Sharity Shoubridge', 'http://dummyimage.com/103x133.bmp/ff4444/ffffff', 'https://ask.com');
insert into books (isbn, title, author, cover, URL) values ('78-307-9133', 'Attack of the Killer Tomatoes!', 'Igor Rumens', 'http://dummyimage.com/155x111.png/ff4444/ffffff', 'https://example.com');
insert into books (isbn, title, author, cover, URL) values ('21-984-4037', 'Missing Picture, The (L''image manquante)', 'Yolane Janecek', 'http://dummyimage.com/229x169.jpg/ff4444/ffffff', 'https://arizona.edu');
insert into books (isbn, title, author, cover, URL) values ('92-875-2433', 'Big Miracle', 'Eunice Burdon', 'http://dummyimage.com/143x125.bmp/cc0000/ffffff', 'https://constantcontact.com');
insert into books (isbn, title, author, cover, URL) values ('25-936-8767', 'Invincible', 'Mead Aidler', 'http://dummyimage.com/189x106.jpg/cc0000/ffffff', 'http://posterous.com');
insert into books (isbn, title, author, cover, URL) values ('95-770-0152', 'Charleston', 'Denys Justun', 'http://dummyimage.com/185x114.bmp/dddddd/000000', 'http://state.tx.us');
insert into books (isbn, title, author, cover, URL) values ('76-190-5027', 'Pandorum', 'Roth Aimer', 'http://dummyimage.com/149x157.jpg/cc0000/ffffff', 'https://cbsnews.com');
insert into books (isbn, title, author, cover, URL) values ('21-484-0624', 'Life of a King', 'Goldina Rabson', 'http://dummyimage.com/166x126.jpg/ff4444/ffffff', 'https://fastcompany.com');
insert into books (isbn, title, author, cover, URL) values ('98-118-5851', 'One-Eyed Monster', 'Kaleb Yerson', 'http://dummyimage.com/205x214.png/cc0000/ffffff', 'http://phpbb.com');
insert into books (isbn, title, author, cover, URL) values ('07-138-2006', 'Reel Bad Arabs: How Hollywood Vilifies a People', 'Rene Antonich', 'http://dummyimage.com/246x129.jpg/cc0000/ffffff', 'https://dailymail.co.uk');
insert into books (isbn, title, author, cover, URL) values ('43-729-8300', 'Heading South (Vers le sud)', 'Jerrie Aubury', 'http://dummyimage.com/242x227.png/cc0000/ffffff', 'https://sina.com.cn');
insert into books (isbn, title, author, cover, URL) values ('66-250-3297', 'The First Men in the Moon', 'Felix Petrillo', 'http://dummyimage.com/122x153.png/ff4444/ffffff', 'https://loc.gov');
insert into books (isbn, title, author, cover, URL) values ('96-662-8307', 'Kozara', 'Tabby Ruppel', 'http://dummyimage.com/218x107.png/5fa2dd/ffffff', 'http://cisco.com');
insert into books (isbn, title, author, cover, URL) values ('50-767-2955', 'Broken Windows', 'Cindelyn Mellhuish', 'http://dummyimage.com/109x227.bmp/dddddd/000000', 'https://gravatar.com');
insert into books (isbn, title, author, cover, URL) values ('81-341-8657', 'I''m Going Home (Je rentre à la maison)', 'Kally Fierro', 'http://dummyimage.com/158x176.bmp/ff4444/ffffff', 'https://devhub.com');
insert into books (isbn, title, author, cover, URL) values ('62-826-5912', 'Mr. Jealousy', 'Tawsha Bilbey', 'http://dummyimage.com/228x222.jpg/cc0000/ffffff', 'http://infoseek.co.jp');
insert into books (isbn, title, author, cover, URL) values ('56-115-6842', 'Skeleton Key, The', 'Leigh Struthers', 'http://dummyimage.com/136x198.bmp/cc0000/ffffff', 'http://uol.com.br');
insert into books (isbn, title, author, cover, URL) values ('38-390-8288', 'Tora-san''s Love Call (Otoko wa tsurai yo: Torajiro koiuta)', 'Zola Facer', 'http://dummyimage.com/179x205.bmp/cc0000/ffffff', 'http://icio.us');
insert into books (isbn, title, author, cover, URL) values ('42-758-4035', 'Urban Legends: Bloody Mary', 'Javier Burberye', 'http://dummyimage.com/192x117.png/dddddd/000000', 'http://house.gov');
insert into books (isbn, title, author, cover, URL) values ('19-611-4853', 'Hitler''s Stealth Fighter', 'Edi Gilberthorpe', 'http://dummyimage.com/221x225.png/5fa2dd/ffffff', 'https://jimdo.com');
insert into books (isbn, title, author, cover, URL) values ('87-158-1846', 'Flu', 'Rahal Ducket', 'http://dummyimage.com/116x192.png/dddddd/000000', 'http://umich.edu');
insert into books (isbn, title, author, cover, URL) values ('66-649-1461', 'Motorcycle Diaries, The (Diarios de motocicleta)', 'Pearline German', 'http://dummyimage.com/239x171.png/dddddd/000000', 'http://hhs.gov');
insert into books (isbn, title, author, cover, URL) values ('73-042-8155', 'K-9', 'Netta Dudderidge', 'http://dummyimage.com/178x225.jpg/5fa2dd/ffffff', 'http://soundcloud.com');
insert into books (isbn, title, author, cover, URL) values ('27-637-0454', 'Last Days, The (Últimos días, Los)', 'Mordy Gullam', 'http://dummyimage.com/123x174.bmp/dddddd/000000', 'https://furl.net');
insert into books (isbn, title, author, cover, URL) values ('40-144-2604', 'Sun on the Horizon', 'Ginevra Asquith', 'http://dummyimage.com/221x118.png/cc0000/ffffff', 'https://japanpost.jp');
insert into books (isbn, title, author, cover, URL) values ('96-519-3727', 'Agony (a.k.a. Rasputin) (Agoniya)', 'Jennine Rennick', 'http://dummyimage.com/176x161.bmp/ff4444/ffffff', 'http://wix.com');
insert into books (isbn, title, author, cover, URL) values ('73-394-3209', 'Mighty Peking Man (a.k.a. Goliathon) (Xing xing wang)', 'Joela Reiling', 'http://dummyimage.com/193x245.png/dddddd/000000', 'https://cdbaby.com');
insert into books (isbn, title, author, cover, URL) values ('70-390-7930', 'DysFunktional Family', 'Quinton Cussins', 'http://dummyimage.com/120x245.png/cc0000/ffffff', 'http://theglobeandmail.com');
insert into books (isbn, title, author, cover, URL) values ('66-452-6526', 'Picnic at Hanging Rock', 'Loni Stuckow', 'http://dummyimage.com/191x127.png/5fa2dd/ffffff', 'https://imgur.com');
insert into books (isbn, title, author, cover, URL) values ('76-371-9087', 'Spiral Staircase, The', 'Ambros Trawin', 'http://dummyimage.com/161x111.png/cc0000/ffffff', 'https://oracle.com');
insert into books (isbn, title, author, cover, URL) values ('65-957-9374', 'All Together', 'Monty Ondrak', 'http://dummyimage.com/107x158.jpg/cc0000/ffffff', 'http://addtoany.com');
insert into books (isbn, title, author, cover, URL) values ('29-053-1993', 'I Hate Valentine''s Day', 'Alyosha Boddis', 'http://dummyimage.com/236x141.bmp/cc0000/ffffff', 'http://dagondesign.com');
insert into books (isbn, title, author, cover, URL) values ('19-169-8939', 'Annie Hall', 'Verena Wedgwood', 'http://dummyimage.com/212x161.bmp/dddddd/000000', 'http://opera.com');
insert into books (isbn, title, author, cover, URL) values ('54-204-1403', 'Blue and the Gray, The', 'Row Assiter', 'http://dummyimage.com/187x170.bmp/5fa2dd/ffffff', 'https://newyorker.com');
insert into books (isbn, title, author, cover, URL) values ('68-763-5318', 'Lawrence of Arabia', 'Milena Giacopetti', 'http://dummyimage.com/168x161.jpg/cc0000/ffffff', 'http://samsung.com');
insert into books (isbn, title, author, cover, URL) values ('08-216-1279', 'Black', 'Teddie Mc Ilory', 'http://dummyimage.com/101x175.jpg/cc0000/ffffff', 'http://tamu.edu');
insert into books (isbn, title, author, cover, URL) values ('77-519-2088', 'Time (Shi gan)', 'Gabbie Rispin', 'http://dummyimage.com/220x135.png/cc0000/ffffff', 'http://edublogs.org');
insert into books (isbn, title, author, cover, URL) values ('57-431-8470', 'Masquerade (Gwanghai, Wangyidoen namja)', 'Zacherie Millyard', 'http://dummyimage.com/174x170.jpg/dddddd/000000', 'https://hugedomains.com');
insert into books (isbn, title, author, cover, URL) values ('29-574-2166', 'Brothers Lionheart, The (Bröderna Lejonhjärta)', 'Brandie Goodee', 'http://dummyimage.com/232x230.jpg/ff4444/ffffff', 'https://is.gd');
insert into books (isbn, title, author, cover, URL) values ('71-952-0676', 'Rat', 'Flori Daborne', 'http://dummyimage.com/106x107.png/cc0000/ffffff', 'https://mapy.cz');
insert into books (isbn, title, author, cover, URL) values ('49-424-7015', 'Somewhere in the City', 'Marleen Scarsbrooke', 'http://dummyimage.com/154x139.bmp/ff4444/ffffff', 'http://oakley.com');
insert into books (isbn, title, author, cover, URL) values ('75-448-3405', 'Nothing Personal', 'Quinta Grichukhin', 'http://dummyimage.com/196x113.bmp/dddddd/000000', 'https://ox.ac.uk');
insert into books (isbn, title, author, cover, URL) values ('48-217-2644', 'Critters 4', 'Jeremie Kraft', 'http://dummyimage.com/218x103.jpg/dddddd/000000', 'https://ovh.net');
insert into books (isbn, title, author, cover, URL) values ('38-029-7604', 'Shock Corridor', 'Imojean Byk', 'http://dummyimage.com/109x178.jpg/cc0000/ffffff', 'https://eepurl.com');
insert into books (isbn, title, author, cover, URL) values ('33-690-8899', 'Page One: Inside the New York Times', 'Tracey Schiesterl', 'http://dummyimage.com/116x171.bmp/dddddd/000000', 'https://google.it');
insert into books (isbn, title, author, cover, URL) values ('11-816-6242', 'Waking Life', 'Augustine Phateplace', 'http://dummyimage.com/146x170.png/dddddd/000000', 'https://go.com');
insert into books (isbn, title, author, cover, URL) values ('65-242-0443', 'Theory of Everything, The', 'Alis Haversham', 'http://dummyimage.com/135x185.bmp/cc0000/ffffff', 'http://wikipedia.org');
insert into books (isbn, title, author, cover, URL) values ('34-704-2689', 'Survival Quest', 'Dennis Gerring', 'http://dummyimage.com/105x205.jpg/dddddd/000000', 'http://scientificamerican.com');
