insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('4976927512', 'How the West Was Fun', 'Tundra', 'San Francisco', 'Mauv');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('1345155522', 'Stay as You Are', '626', 'Tupsan', 'Puce');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('6167327327', 'Return of the Living Dead: Necropolis', 'Envoy XL', 'Beiyang', 'Orange');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('9229280801', 'High, Wide, and Handsome', 'SLK-Class', 'Menggala', 'Yellow');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('8876512209', 'Bill Bailey: Qualmpeddler', 'M-Class', 'Tulyushka', 'Pink');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('1805522027', 'Angel', 'Century', 'Zouma', 'Mauv');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('5200676746', 'Hell to Eternity', 'F250', 'Villa Ojo de Agua', 'Crimson');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('6795675815', 'To the Limit (Am Limit)', 'Town & Country', 'Gedongmulyo', 'Violet');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('2111089265', 'Hannah Takes the Stairs', 'F-Series', 'Tonshayevo', 'Orange');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('3366173823', 'More', 'Leaf', 'Manicaragua', 'Crimson');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('1193458307', 'Heat and Dust', 'T100 Xtra', 'Ponikiew', 'Puce');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('9906806893', 'Blackout', 'Safari', 'Cruz Alta', 'Green');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('7714255188', 'Big Boss, The (Fists of Fury) (Tang shan da xiong)', 'MKZ', 'Al Qurayn', 'Purple');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('0994272340', 'Cabin Fever: Patient Zero', '650', 'Dýšina', 'Mauv');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('1343954991', 'Vanquished, The (I vinti)', 'Ridgeline', 'Lyon', 'Yellow');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('9264177507', 'A Viking Saga: The Darkest Day', 'Crown Victoria', 'Qiting', 'Aquamarine');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('4475361990', 'Me and My Sister', 'MKX', 'Kali', 'Khaki');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('2414004525', 'Sinbad and the Eye of the Tiger', 'Maxima', 'Gornji Breg', 'Indigo');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('4374272038', 'Everlasting Moments (Maria Larssons eviga ögonblick)', 'STS', 'Cachí', 'Mauv');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('2795919494', 'Mr. Vampire (Geung si sin sang)', 'Lucerne', 'Baipenzhu', 'Puce');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('7548411049', 'Rocket Science', 'Cabriolet', 'Sevilla', 'Blue');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('9996450317', 'Silent Night, Deadly Night', 'Ram 2500 Club', 'Novoselë', 'Pink');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('2105419488', 'Sexy Nights of the Living Dead', 'Sunbird', 'Sing Buri', 'Puce');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('6036168624', 'Chinoise, La', 'Versa', 'Spasskoye', 'Red');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('1602078521', 'Chinese Zodiac (Armour of God III) (CZ12)', 'GTO', 'Tokombere', 'Orange');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('7552958693', 'Shane', 'Metro', 'Caobi', 'Pink');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('8006015554', 'Lola', 'RDX', 'Jovellar', 'Fuscia');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('7848368106', 'Monster Squad, The', 'Grand Caravan', 'Petrópolis', 'Pink');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('3876811716', 'After Porn Ends', 'Alero', 'San Cristóbal', 'Crimson');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('1406289094', 'My Dog Skip', 'Camaro', 'Marshintsy', 'Puce');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('7703299855', 'Beverly Hillbillies, The', 'Intrepid', 'Aveleda', 'Khaki');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('0205305857', 'Vares: Private Eye (Vares - Yksityisetsivä)', 'Celica', 'Novi Bečej', 'Green');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('6976912193', 'I Am Fishead', 'CTS-V', 'Kozakai-chō', 'Goldenrod');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('1708223827', 'New Orleans Uncensored', 'Monte Carlo', 'Ojo de Agua', 'Khaki');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('5500741888', 'Divorce of Lady X, The', 'Festiva', 'San José de Bocay', 'Pink');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('7412432176', 'Mortadelo & Filemon: The Big Adventure (La gran aventura de Mortadelo y Filemón)', 'CT', 'Zhenzhushan', 'Pink');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('1669216578', 'Week-End at the Waldorf', 'CL-Class', 'Jengglungharjo', 'Blue');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('9604444298', 'Poison Ivy: New Seduction', 'Special', 'Huangge', 'Indigo');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('6231380564', 'Timerider: The Adventure of Lyle Swann', 'V50', 'Hondo', 'Orange');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('5186030767', 'Prisoner of Zenda, The', 'Avalon', 'Asmara', 'Red');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('8422927675', 'Group, The', 'Ram 1500', 'Apartadó', 'Khaki');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('0381050238', 'Split, The', 'Civic', 'Soledar', 'Violet');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('7326086443', 'Last Laugh, The (Letzte Mann, Der)', 'Q', 'Fukayachō', 'Puce');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('1895493501', 'Six Degrees of Separation', 'Integra', 'Atescatempa', 'Turquoise');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('2262183058', 'David Cross: Let America Laugh', 'Camaro', 'Owerri', 'Blue');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('5080314958', 'Cet amour-là', 'GranTurismo', 'Bacalan', 'Crimson');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('9629274957', 'Broken Sky (El cielo dividido)', 'Jetta', 'Lago da Pedra', 'Teal');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('8892228579', 'Riders of Destiny', '430', 'Yiyang', 'Mauv');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('1484367723', 'Snake-Crane Secret (She hao dan xin zhen jiu zhou)', 'Jimmy', 'Lampa', 'Fuscia');
insert into user_preferences (userID, comedy, thriller, fantasy, romance) values ('8037167909', 'Devil Hunter (El caníbal)', 'DeVille', 'Qiucun', 'Aquamarine');
